### ISSUE TITLE
Save image bug

### ISSUE THREAD

**Issue by kittinan** [narze/bkk-sticker#1]
The saved image has transparent padding on the left.
```
OS: Ubuntu 20.04
Browser: Google Chrome Version 125.0.6422.112 (Official Build) (64-bit)
Screen size: 1920x1080
```

![Screenshot at 2024-05-29 21-35-50](https://github.com/narze/bkk-sticker/assets/144775/225f0b6c-398c-4e83-a0cb-0325f59d5ea8)

**Comment by narze** [comment]
Should be fixed by https://github.com/narze/bkk-sticker/commit/1af537b193506c52e3c044b1c21f38942e45e002
I also change image to .jpg to save some space

**Comment by kittinan** [comment]
🙏🙏🙏
